### ISSUE TITLE
python3 cannot load libSplashKit.dylib on macOS

### ISSUE THREAD

**Issue by alexcu** [splashkit/splashkit-core#100]
@macite Was playing around with SplashKit for python3 on macOS. The `.splashkit/commands/python3/splashkit.py` file cannot load the dylib for `cdll.LoadLibrary` and `CDLL` calls:

```
$ skm python3 hello_world.py
Traceback (most recent call last):
  File "hello_world.py", line 1, in <module>
    from splashkit import *
  File "/Users/Alex/.splashkit/commands/python3/splashkit.py", line 4, in <module>
    cdll.LoadLibrary("libSplashKit.dylib")
  File "/Users/Alex/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/ctypes/__init__.py", line 422, in LoadLibrary
    return self._dlltype(name)
  File "/Users/Alex/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/ctypes/__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libSplashKit.dylib, 6): image not found
```

The image is not being found despite `PYTHON_PATH` being set. Even if I try and run this without skm, I'm seeing the same thing:

```
DYLD_LIBRARY_PATH="/Users/Alex/.splashkit/lib" PYTHONPATH=/Users/Alex/.splashkit/commands/python3 python3 hello_world.py
```

I manually fixed this by making them absolute paths (obviously not the right solution here).

```python
from ctypes import *
from enum import Enum

cdll.LoadLibrary("/Users/Alex/.splashkit/lib/libSplashKit.dylib")
sklib = CDLL("/Users/Alex/.splashkit/lib/libsplashkit.dylib")
```

It seems that the `DYLD_LIBRARY_PATH` does not have an affect on python3 (possibly due to El Capitan's System Integrity Protection? See [here](https://github.com/nteract/nteract/issues/1523) and [here](https://github.com/rstudio/reticulate/issues/96)).

Any ideas? Does this work for you?

**Comment by macite** [comment]
@alexcu did you manage to try testing this outside of the Anaconda python environment?

**Comment by alexcu** [comment]
Have not yet had a chance… will do as soon as I can
