### ISSUE TITLE
BUG: Error message when calling non-loaded resource has incorrect path

### ISSUE THREAD

**Issue by Franknsten** [splashkit/splashkit-core#101]
Platform: 64 bit Windows 10, using Mingw-w64 64bit terminal

When a resource (image/sound) is called to be drawn/played, but has not been loaded, the error message displays with /Users/acain/, instead of /Users/{USER}/ 

For example, calling 
`play_sound_effect("boing")`
But without a sound effect called "Boing" is loaded gives 
`(08/19/2018) WARN  -> Play Sound Effect called, but no valid sound effect supplied [C:/Users/acain/Documents/Code/splashkit/coresdk/src/coresdk/sound.cpp:131]`
as an error

**Comment by macite** [comment]
Yeah, not sure how we can fix this as these are baked in when compiled. It makes sense as a log, as it is technically for the library developer - but doesn't work in our context.

**Comment by macite** [comment]
Fixed in latest build - will push new version soon.
