### ISSUE TITLE
[POTENTIAL BUG] Specific quote mark needed to load/access resources

### ISSUE THREAD

**Issue by Franknsten** [splashkit/splashkit-core#102]
I'm not sure if this is intended behavior or not, but I couldn't find anything explicitly stating to use " instead of '

When using SplashKit to load resources (`load_music()`, `load_sound_effect()`,` load_bitmap()`) or access them (`play_music()`, `play_sound_effect()`, `draw_bitmap()` ), if the string arguments (Name, Filename) are passed using the single quote (') the following message is displayed

```
program.cpp:23:29: warning: character constant too long for its type
  load_sound_effect("clock", 'tick.flac');
                             ^~~~~~~~~~~
program.cpp: In function 'void load_sounds()':
program.cpp:23:40: error: invalid initialization of reference of type 'const string& {aka const std::__cxx11::basic_string<char>&}' from expression of type 'int'
  load_sound_effect("clock", 'tick.flac');
                                        ^
In file included from C:\msys64\home\Isaac\.splashkit\commands\clang++\include/splashkit.h:39:0,
                 from program.cpp:1:
C:\msys64\home\Isaac\.splashkit\commands\clang++\include/sound.h:22:14: note: in passing argument 2 of '_sound_effect_data* load_sound_effect(const string&, const string&)'
 sound_effect load_sound_effect(const string &name, const string &filename);

```

If this is the intended behavior (I'm not familiar with how c++ handles strings with the different quotes, so this could be unavoidable), it would be good to mention it in the documentation for the functions affected

**Comment by macite** [comment]
' in c++ is used for single characters so 'a' for example. Use " for all strings :)
