### ISSUE TITLE
rnd(int min, int max) errors with 'symbol(s) not found for architecture x86_64'

### ISSUE THREAD

**Issue by astrojuno** [splashkit/splashkit-core#107]
rnd(int min, int max) function fails to compile with error:
```
Undefined symbols for architecture x86_64:
  "rnd(int, int)", referenced from:
      _main in program-85e044.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Git cloned and rnd(int min, int max) function copied and pasted directly into program and no errors reported. 

To reproduce error:
- mkdir playground
- cd playground/
- skm new c++
- open folder in vscode
- paste the following into main():
`int my_rand = rnd(10, 20);`
- save and compile

Using macOS 10.14.6, vscode 1.36.1

**Comment by macite** [comment]
Fixed... run **skm update** and try again.

**Comment by astrojuno** [comment]
Hi Andrew,
I'm a student in your SIT102 class. I was interested in suggesting a fix
for this, but couldn't see the problem. Looking at the GitHub code now I
can't see what you've changed.

Just because I'm curious, could you tell me what you did? It's your code,
so no stress if you'd rather not...

Cheers,
John.

**Comment by macite** [comment]
Happy to discuss - it was just an issue that I hadn't built the library. I also needed to fix an issue with linking on older versions of macOS, so I fixed the build script (cmake) recompiled and added the new library.

There are some changes we need to make... if you are interested I'd be happy to help provide the issue and how to approach it.

**Comment by astrojuno** [comment]
Thanks Andrew, appreciate the explanation!
I'd love to help, and any advice you could give. I would qualify it with
two statements:
- My workload is quite large, so please don't issue me anything with a
tight timeframe;
- I'm quite new to git, so particularly the first time I'll probably have
to ask a few annoying questions.

If that still works, it'd be great to be involved!
Cheers,
John.

**Comment by macite** [comment]
Sorry I haven't had time to get back to you. One thing you could work on is the issue with draw_text (without a font) - at the moment it uses sdl_gfx that fails. 

Give this a test - create two windows. Try drawing text to each.

The problem is that the text character textures are only loaded for one window - so drawing text to any other window fails. What we need to do is re-implement draw_text within SplashKit using SplashKit Bitmaps. See if you can replicate the issue first.
