### ISSUE TITLE
Feature: Radian versions of functions

### ISSUE THREAD

**Issue by hugglesfox** [splashkit/splashkit-core#110]
It would be nice if there were radian versions of `sine()`, `cosine()`, etc. as radians are easier to work with and are what's taught in highschool trig. Also it would clean up code as then I'm not constantly converting radians to degrees 😝

**Comment by macite** [comment]
Happy to accept a PR on this. My suggestion is to add a "trigonometry mode" setting that allows the user to switch ALL functions between degrees or radians. You would need to check all uses of these functions within the code itself to make sure they continue to work in both modes.

**Comment by hugglesfox** [comment]
On second thoughts it would be better just to direct people to the trig functions provided by `cmath` rather then to add extra complexity to splashkit. We could add a note in the documentation about the `cmath` library I don't think that's necessary.  
Thanks for your contributions Andrew.
