### ISSUE TITLE
No License.

### ISSUE THREAD

**Issue by monoxane** [splashkit/splashkit-core#141]
This repository is aimed at beginners but does not have a license file in it, a lack of license is legally implicit absolute copyright for all content by its original authors which results in literally everyone forking or cloning this code to be in violation of the copyright law of the US (GitHub and the code location), and Australia (Organization location and presumed majority of the users).

Please rectify this or a number of people will be unable to continue coursework from the university.

**Comment by alexcu** [comment]
Resolved with 9d52e75
