### ISSUE TITLE
draw_text overload fails to resize font.

### ISSUE THREAD

**Issue by CamHowling** [splashkit/splashkit-core#145]
draw_text overload does not resize font based on integer input parameter for the following overload:

draw_text(text: string, clr: color, fnt: string, font_size: int, x: double, y: double, opts: drawing options).

Had code: 

            draw_text("GAME OVER", COLOR_RED, "NORMAL_FONT",  30, 500.0, 400.0, option_to_screen());
            draw_text("GAME OVER", COLOR_RED, "NORMAL_FONT",  50, 500.0, 450.0, option_to_screen());
            draw_text("GAME OVER", COLOR_RED, "NORMAL_FONT",  100, 500.0, 500.0, option_to_screen());
            draw_text("GAME OVER", COLOR_RED, "NORMAL_FONT",  200, 500.0, 550.0, option_to_screen());

![SpaceGame_wej9hDcZYw](https://user-images.githubusercontent.com/15999072/150311196-1bbb5056-b6bf-4ead-9fdb-d7571f8cc884.png)

**Comment by rickydodd** [comment]
It appears that you're passing an incorrect argument. Where you have passed "NORMAL_FONT", this is supposed to be a font; it's instead resorting to a fallback bitmap. I can look further into whether the default bitmap can be made resizeable, but, for now, this should resolve your problem:

```
load_font("arial", "arial.ttf");

draw_text("GAME OVER", COLOR_RED, "arial",  30, 500.0, 400.0, option_to_screen());
draw_text("GAME OVER", COLOR_RED, "arial",  50, 500.0, 450.0, option_to_screen());
draw_text("GAME OVER", COLOR_RED, "arial",  100, 500.0, 500.0, option_to_screen());
draw_text("GAME OVER", COLOR_RED, "arial",  200, 500.0, 550.0, option_to_screen());

free_all_fonts();
```

If you want to change font style (normal, italic, bold, ...):
```
load_font("arial", "arial.ttf");
set_font_style("arial", ITALIC_FONT);

draw_text("GAME OVER", COLOR_RED, "arial",  30, 500.0, 400.0, option_to_screen());
draw_text("GAME OVER", COLOR_RED, "arial",  50, 500.0, 450.0, option_to_screen());
draw_text("GAME OVER", COLOR_RED, "arial",  100, 500.0, 500.0, option_to_screen());
draw_text("GAME OVER", COLOR_RED, "arial",  200, 500.0, 550.0, option_to_screen());

free_all_fonts();
```

load_font() can also return a font, which can make fonts easier to manage:
```
font fnt = load_font("arial", "arial.ttf");
set_font_style(fnt, ITALIC_FONT);

draw_text("GAME OVER", COLOR_RED, fnt,  30, 500.0, 400.0, option_to_screen());
draw_text("GAME OVER", COLOR_RED, fnt,  50, 500.0, 450.0, option_to_screen());
draw_text("GAME OVER", COLOR_RED, fnt,  100, 500.0, 500.0, option_to_screen());
draw_text("GAME OVER", COLOR_RED, fnt,  200, 500.0, 550.0, option_to_screen());

free_all_fonts();
```

You can also look at using non-local fonts using `download_font(const string &name, const string &url, unsigned short port)` ([documentation ref](https://splashkit.io/api/networking/#download-font)).

**Comment by jakerenzella** [comment]
@rickydodd  thanks for responding to this. Have you tested this yourself? Is it possible OP loaded a font called "NORMAL_FONT"? 

I just recall a while back there were definitely some inconsistencies with some of the font drawing APIs related to this but my memory is hazy on this one... I remember thinking there was something we needed to fix.

What if you pass in a font variable and not a string?

**Comment by jakerenzella** [comment]
(Might just be a documentation issue)

**Comment by rickydodd** [comment]
@jakerenzella Here's one of the minimum-viable tests I performed that tried to remain as true to the original as possible:

```
#include "splashkit.h"

int main()
{
    open_window("Testing Text", 2000, 1000);
    
    load_font("NORMAL_FONT", "arial.ttf");

    draw_text("GAME OVER", COLOR_RED, "NORMAL_FONT",  30, 500.0, 400.0, option_to_screen());
    draw_text("GAME OVER", COLOR_RED, "NORMAL_FONT",  50, 500.0, 450.0, option_to_screen());
    draw_text("GAME OVER", COLOR_RED, "NORMAL_FONT",  100, 500.0, 500.0, option_to_screen());
    draw_text("GAME OVER", COLOR_RED, "NORMAL_FONT",  200, 500.0, 550.0, option_to_screen());
    
    refresh_screen();

    delay(10000);

    free_all_fonts();

    return 0;
}
```

Result:
![image](https://user-images.githubusercontent.com/63101193/159143960-01804189-01d0-4908-be8b-f18557e15839.png)

After digging around the core a little last night, it just appeared that this was an instance of an incorrect argument passed (specifically a simple mistake of confusing the font style, such as the enums NORMAL_FONT, etc, for a defined font), and that it was instead defaulting to a default bitmap in the instance that a font is not defined. I didn't spend enough time, however, trying to determine whether I could resize the default bitmap myself.

**Comment by jakerenzella** [comment]
I think your edit is the issue I'm recalling! Thanks for your efforts. Should we make a new issue with this?

**Comment by CamHowling** [comment]
@jakerenzella, @rickydodd Thanks for following this up - I can confirm it was mostly a user and documentation issue - with a splash of inheriting a base project/existing code.

**Comment by macite** [comment]
I suggest we close this issue - and create a new one in relation to the undefined font parameter.
