### ISSUE TITLE
Cannot convert point_2d to vector_2d (and vice versa)

### ISSUE THREAD

**Issue by CamHowling** [splashkit/splashkit-core#146]
Assignment of a point_2d object to a vector_2d object is not supported.
Assignment of a vector_2d object to a point_2d object is not supported.
These objects types are functionally identical, and many use cases benefit from conversion.

**Comment by CamHowling** [comment]
Note: [vector_to()](https://splashkit.io/api/physics/#group-vector-to) can provide some of the functionality of this issue.

**Comment by macite** [comment]
With the need to support cross-language libraries, we want things explicitly converted between different types.
