### ISSUE TITLE
Sprite At C# not returning ture when sprite XY at point2D XY

### ISSUE THREAD

**Issue by DaGoblin** [splashkit/splashkit-core#157]
Appears to be an issue with https://splashkit.io/api/sprites/#sprite-at not returning true when sprites XY arrives at the target location.
Just listing, for now, I might try looking at the behind-the-scenes later. The signature feels a bit off on splashkit.io documentation as well. i.e. 
`public static bool Sprite.SpriteAt(Sprite s, Point2D pt);
public static bool SplashKit.SpriteAt(Sprite s, Point2D pt);`
the first signature doesn't seem to be valid also if you're using a sprite you shouldn't need to pass a sprite in.

My sample code for the issue of not returning true
`                foreach (Sprite s in _ShipList)
                {
                    Console.WriteLine("Sprite Location" + s.X + " " + s.Y);
                    Point2D ArrivedPoint = new Point2D { X = s.X, Y = 200 };
                    Console.WriteLine("Arrivale Point " + ArrivedPoint.X + " " + ArrivedPoint.Y);
                    Console.WriteLine(SplashKit.SpriteAt(s, ArrivedPoint));
                    if (SplashKit.SpriteAt(s, ArrivedPoint)) { s.Dy = 0; Console.WriteLine("Has Arrived"); }
                    else nextPhase = false;
                }`
Console output where it should be true plus before after.

Sprite Location1000 198
Arrivale Point 1000 200
False
Sprite Location200 200
Arrivale Point 200 200
False
Sprite Location600 200
Arrivale Point 600 200
False
Sprite Location1000 200
Arrivale Point 1000 200
False
Sprite Location200 202
Arrivale Point 200 200
False

**Comment by macite** [comment]
SpriteAt executes a point collision with the sprite - if you just want to test if the position of the sprite equals a given point then you can do that using point comparison.

It would be great to update the documentation to indicate this more clearly.
