### ISSUE TITLE
Silent failure on build

### ISSUE THREAD

**Issue by Brunius** [splashkit/splashkit-core#99]
I am encountering an issue when building projects using skm. It seems that on my particular system, it fails silently - always. A successful build will provide the "dotnet command run successfully" message, but an unsuccessful build will provide no message - simply a blank line.

I am using MINGW64 on Windows 10, and the latest version of Splashkit, downloaded today.
Using the computers at uni on the same project does not manifest the same problem, so I believe this is likely related to my particular setup.
![image](https://user-images.githubusercontent.com/29041387/31471718-f7e46c98-af35-11e7-9545-31db37a464a1.png)
At top is an unsuccessful build, at bottom a successful one.

Please let me know if I can provide any further information to help with this problem.

**Comment by jakerenzella** [comment]
Hi @Brunius - I may have pushed a fix for this, could you execute `skm update` (you should see 1 file change after the update), and then try again and let me know the results?

**Comment by Brunius** [comment]
Hi @jakerenzella, thanks for taking this on. I have updated splashkit, and it has helped...to an extent.

![image](https://user-images.githubusercontent.com/29041387/31519586-8659cf78-afee-11e7-8996-bad983484bc6.png)

This is better than a silent failure, but what I'm really hoping for is the verbose output many compilers give (I can't find this method you reference on line 200, missing semicolon, etc.).

**Comment by jakerenzella** [comment]
@Brunius Could you run `dotnet` commands such as `build` without `skm` and see if it is working as expected? It seems like it should be printing out errors here.

**Comment by Brunius** [comment]
The raw `dotnet` commands seem to work - 


Brunius@PERCIVAL-PC MINGW64 /my/project/path/project (master)
$ skm dotnet build

[32minfo[39m: dotnet command run successfully

Brunius@PERCIVAL-PC MINGW64 /my/project/path/project (master)
$ dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  game-of-grades -> my\project\path\project\bin\Debug\netcoreapp2.0\game-of-grades.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.75

**Comment by macite** [comment]
I've had a look into this and can't replicate the problem, so its a little hard to test. It seems like the output from the dotnet program are not being passed through to your standard output (and standard error) streams.

Can you tell us more about your setup? Are you using the standard msys2 terminal?

**Comment by Brunius** [comment]
Apparently not. I have been using git-bash, which is where this problem occurs. When using the normal msys2 terminal, it does not happen - the full error log is printed. So I guess you can mark this down as "not our problem" and move on? I've got a work-around, at least.
